use startersql;

select * from sales;
-- 1.	View the first 10 rows of the dataset.
select * from sales limit 50;

-- 2.	How many records are there in total?
select count(*) from sales;

-- 3.	List all unique regions.
select distinct region from sales;

-- 4.	List all unique item types.
select distinct  Item_Type from sales;

-- 5.	Show all records where the sales channel is Online.
select * from sales where  Sales_Channel="online";

-- 6.	Show all records where the order priority is High (H).
select * from sales where Order_Priority="H";
select * from sales;
-- 7.	Count how many sales records exist for each region.
select region,count(*) from sales group by region ;

-- 8.	What is the average unit cost for each item type?
select Item_Type, avg(Unit_Cost) as avgunit_cost from sales group by Item_Type;

-- 9.	Find the total profit generated by each country.
select Country, sum(Total_Profit) from sales group by Country;

-- 10.	List the top 5 countries by total revenue.
select Country, sum(Total_Revenue) from sales group by Country limit 5;

-- 11.	How many sales were made through each sales channel?
select Sales_Channel from sales group by Sales_Channel;

-- 12.	Which item types were sold in the Offline channel?
select Item_Type from sales where Sales_Channel="offline";

-- 13.	Which region has the highest total revenue?
select Region, max(Total_Revenue)from sales group by Region limit 1;

-- 14.	Which item type has the highest total profit?
select Item_Type, max(Total_Profit)from sales group by Item_Type limit 1;

-- 15.	Calculate the profit margin (Total_Profit / Total_Revenue) for each item type.
select Item_Type, sum(Total_Profit / Total_Revenue) As profit_margin from sales group by Item_Type limit 1;

-- 16.	What is the average total revenue per region and sales channel?
select Region, Sales_Channel,avg(Total_Revenue)As total_revenue_avg from sales group by Region, Sales_Channel; 

-- 17.	Show the top 3 countries by average profit per sale.
select Country, avg(Total_Profit) from sales group by Country limit 3;

-- 18.	Find the most profitable country for each region.
select Country, sum(Total_Profit)from sales group by Country limit 3;

-- 19.	Compare total revenue for Online vs Offline sales per region.


-- 20.	Find item types that were sold in more than 5 different countries.


-- 26.	What is the total profit for each order priority level?
select * from sales;
select Order_Priority, sum(Total_Profit) from sales group by Order_Priority;

-- 27.	Which three item types have the lowest average unit cost?
select Item_Type, avg(Unit_Cost) from sales group by Item_Type order by Item_Type asc limit 3;

-- 28.	Find the number of countries in each region.
select Region, count( DISTINCT Country) as cou from sales group by Region order by cou ;

-- 30.	What is the average total profit for each shipping priority (Order_Priority)?
select Order_Priority, avg(Total_Profit) as avg_total from sales group by Order_Priority;
select * from sales;
-- 31.	Show all records where the unit cost is above 500.
select * from sales where Unit_Cost >500 ;

-- 32.	Show all orders where profit is less than 20% of revenue.
SELECT * FROM sales WHERE Total_Profit < 0.2 * Total_Revenue;

-- 33.	List all countries that had orders with a unit cost below 100.
select Country, Unit_Cost from sales where  Unit_Cost < 100 ;

-- 34.	Show records where the item type is "Baby Food" and sales channel is "Offline".
select * from sales where Item_Type="Baby Food" and Sales_Channel="Offline";

-- 35.	Find all orders where the country is not in Asia.
select * from sales where Region!='Asia';

-- ________________________________________
-- 📌 Sorting & Limiting
select * from sales;
-- 36.	Show the 10 most profitable orders (by Total_Profit).
select * from sales order by Total_Profit asc limit 10 ;

-- 37.	List the 5 countries with the lowest total revenue.
select Country,Total_Revenue from sales order by Total_Revenue asc  ;

-- 38.	Show top 3 regions by total number of orders.
select Region, count(*) from sales  group by Region limit 3;

-- 39.	List item types sorted by their average unit cost in descending order.
select Item_Type, avg(Unit_Cost) from sales group by Item_Type order by Item_Type desc;

-- 40.	Find the 5 earliest shipping dates and the corresponding countries.
SELECT 
    Ship_Date,
    Country
FROM sales
ORDER BY Ship_Date ASC
LIMIT 5;
